CREATE TABLE SAGA_INSTANCE (
    ID             VARCHAR2(36 CHAR) PRIMARY KEY,
    SAGA_TYPE      VARCHAR2(100 CHAR) NOT NULL,
    STATUS         VARCHAR2(40 CHAR) NOT NULL,
    CORRELATION_ID VARCHAR2(100 CHAR),
    STARTED_AT     TIMESTAMP(6) NOT NULL,
    COMPLETED_AT   TIMESTAMP(6),
    LAST_ERROR     VARCHAR2(2000 CHAR)
);

CREATE TABLE SAGA_STEP (
    ID                  VARCHAR2(36 CHAR) PRIMARY KEY,
    SAGA_ID             VARCHAR2(36 CHAR) NOT NULL,
    STEP_ORDER          NUMBER(10) NOT NULL,
    HTTP_METHOD         VARCHAR2(10 CHAR) NOT NULL,
    REQUEST_URL         VARCHAR2(2000 CHAR) NOT NULL,
    COMPENSATION_URL    VARCHAR2(2000 CHAR) NOT NULL,
    REQUEST_BODY        CLOB,
    RESPONSE_BODY       CLOB,
    RESPONSE_STATUS     NUMBER(5),
    STATUS              VARCHAR2(40 CHAR) NOT NULL,
    CREATED_AT          TIMESTAMP(6) NOT NULL,
    UPDATED_AT          TIMESTAMP(6) NOT NULL,
    CONSTRAINT FK_SAGA_STEP_INSTANCE FOREIGN KEY (SAGA_ID) REFERENCES SAGA_INSTANCE(ID),
    CONSTRAINT UK_SAGA_STEP_ORDER UNIQUE (SAGA_ID, STEP_ORDER)
);

CREATE INDEX IX_SAGA_STEP_STATUS ON SAGA_STEP (SAGA_ID, STATUS, STEP_ORDER);

CREATE TABLE SAGA_COMP_TASK (
    ID              VARCHAR2(36 CHAR) PRIMARY KEY,
    SAGA_ID         VARCHAR2(36 CHAR) NOT NULL,
    STEP_ID         VARCHAR2(36 CHAR) NOT NULL,
    STATUS          VARCHAR2(40 CHAR) NOT NULL,
    NEXT_ATTEMPT_AT TIMESTAMP(6) NOT NULL,
    RETRY_COUNT     NUMBER(10) DEFAULT 0 NOT NULL,
    LOCKED_AT       TIMESTAMP(6),
    LOCKED_BY       VARCHAR2(200 CHAR),
    LAST_ERROR      VARCHAR2(2000 CHAR),
    CREATED_AT      TIMESTAMP(6) NOT NULL,
    UPDATED_AT      TIMESTAMP(6) NOT NULL,
    CONSTRAINT FK_COMP_TASK_SAGA FOREIGN KEY (SAGA_ID) REFERENCES SAGA_INSTANCE(ID),
    CONSTRAINT FK_COMP_TASK_STEP FOREIGN KEY (STEP_ID) REFERENCES SAGA_STEP(ID),
    CONSTRAINT UK_COMP_TASK_STEP UNIQUE (STEP_ID)
);

CREATE INDEX IX_COMP_TASK_POLL ON SAGA_COMP_TASK (STATUS, NEXT_ATTEMPT_AT, LOCKED_AT);

CREATE TABLE DEMO_PAYMENT (
    ID          VARCHAR2(36 CHAR) PRIMARY KEY,
    CUSTOMER_NO VARCHAR2(30 CHAR) NOT NULL,
    AMOUNT      NUMBER(19,2) NOT NULL,
    STATUS      VARCHAR2(30 CHAR) NOT NULL,
    CREATED_AT  TIMESTAMP(6) NOT NULL
);

CREATE TABLE DEMO_REMOTE_OPERATION (
    STEP_ID       VARCHAR2(36 CHAR) PRIMARY KEY,
    SAGA_ID       VARCHAR2(36 CHAR) NOT NULL,
    OPERATION_TYPE VARCHAR2(50 CHAR) NOT NULL,
    CUSTOMER_NO   VARCHAR2(30 CHAR) NOT NULL,
    AMOUNT        NUMBER(19,2) NOT NULL,
    STATUS        VARCHAR2(30 CHAR) NOT NULL,
    CREATED_AT    TIMESTAMP(6) NOT NULL,
    COMPENSATED_AT TIMESTAMP(6)
);
